### ISSUE TITLE
English Readme

### ISSUE THREAD

**Issue by besendorf** [elvesrodrigues/scrapy-tor-ip-rotator#1]
Hey, 
this seems really usefull. Could you maybe translate the Readme to english?
Thank you very much

**Comment by SparseSpeculator** [comment]
I would also welcome that! :)

**Comment by elvesmrodrigues** [comment]
Hi, @besendorf and @SparseSpeculator! 

First of all, sorry for the delay in answering. 

I didn't expect this project to be used by other people, and in the context of its creation, it was a requirement to use my native language for its documentation, Brazilian Portuguese.

But I will provide a new up-to-date version documented in English.

Thank you!
